version: '3.9'

services:
  web:
    container_name: pi-web
    build: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  db: 
    container_name: pi-db
    image: postgres
    environment:
      POSTGRES_USER: pi
      POSTGRES_DB: pi
      POSTGRES_PASSWORD: pi
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    container_name: pi-adminer
    image: adminer
    ports:
      - 8080:8080

  db-mysql:
    container_name: pi-db-mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pi
      MYSQL_DATABASE: pi-db
      MYSQL_USER: pi
      MYSQL_PASSWORD: pi
    volumes:
      - ./db-mysql:/var/lib/mysql
